disabled_rules:
- line_length
- trailing_whitespace
- function_body_length
- empty_enum_arguments
- force_cast
- nesting
- type_name

excluded:
  - Sources/Application/AppDelegate.swift
  - Sources/Application/SceneDelegate.swift

identifier_name:
    excluded:
        - id
